<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="mohammedathera" name="appium_pack.TimeOut" tests="3" failures="0" timestamp="16 May 2020 15:40:17 GMT" time="0.242" errors="1">
  <testcase name="testcase3" time="0.003" classname="appium_pack.TimeOut"/>
  <testcase name="testcaes2" time="0.014" classname="appium_pack.TimeOut"/>
  <testcase name="testcase1" time="0.225" classname="appium_pack.TimeOut">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method appium_pack.TimeOut.testcase1() didn&#039;t finish within the time-out 200">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method appium_pack.TimeOut.testcase1() didn't finish within the time-out 200
]]>
    </error>
  </testcase> <!-- testcase1 -->
</testsuite> <!-- appium_pack.TimeOut -->
